### ISSUE TITLE
"Add VPN" button buggy after configuration error

### ISSUE THREAD

**Issue by jlnr** [elementary/switchboard-plug-network#122]
Importing OpenVPN files can require a bit of trial-and-error (see #18). When importing a profile fails, an error message appears, and afterwards the "+" button below the VPN list is disabled. This can be reproduced by importing any random file that is not a valid OpenVPN config.

When I then go back to "All Settings" and come back to "Network", the button is sometimes enabled, but clicking it spawns the config dialogs *behind* the settings window. The only way to make it work reliably is to completely reopen system settings.

**Comment by arshubham** [comment]
@jlnr I am unable to reproduce a case where the add button is disabled. However I have further removed the possibility for it happening in #208 . As for the window appearing in the back, the plug has no control over it, since it is an external application.

**Comment by jlnr** [comment]
@arshubham Awesome, I have a long weekend upcoming and I'm looking forward to giving your branch a spin. :+1:
