### ISSUE TITLE
Password field shouldn't validate when user has not interacted with the entery even once.

### ISSUE THREAD

**Issue by arshubham** [elementary/switchboard-plug-network#127]
On trying to connect a WPA2 secured network the password field is auto selected and validates the text even without user input showing a red border. On the first glance it seems that something is wrong with the network. 

Possible solutions:
1. Only start validating after first user input.
2. Since in this field we enter a password only known to us, it can't be right or wrong which the red border implies, instead ask user to check the password if it is less than 8 characters (preferably with a tool-tip), saying the a WPA2 password is always >8 characters.

![image](https://user-images.githubusercontent.com/14235191/42256193-6c6dfcb6-7f6d-11e8-97a2-2462a78c8af1.png)

OS: juno-beta1

**Comment by danrabbit** [comment]
This dialog comes from NetworkManager, so there's nothing that we can do about its behavior in this repo.

Closing as "Out of Scope" since the behavior occurs in an upstream component and not in this repo
