### ISSUE TITLE
Airplane mode swapped after reboot

### ISSUE THREAD

**Issue by drewsucksatlife** [elementary/switchboard-plug-network#129]
Whenever I enable airplane mode and reboot the system, network is enabled and I'm able to connect to any wireless network, but when I go to settings and look at airplane mode settings, they are turned on, but when I turn off airplane mode, airplane mode gets enabled. After a reboot, everything returns to normal.

**Comment by SneWs** [comment]
I've not been able to reproduce this using latest bits from Juno. Could you @drewsucksatlife try again with latest bits from the Juno beta?

**Comment by drewsucksatlife** [comment]
@SneWs Sure, I’ll test it when I get home.

**Comment by SneWs** [comment]
Did you test this @drewsucksatlife?

**Comment by drewsucksatlife** [comment]
Unable to reproduce the issue now.
