### ISSUE TITLE
Edit gtk.notebook

### ISSUE THREAD

**Issue by ItsPossibleAlready** [elementary/switchboard-plug-network#131]
![2018-09-21 22-17-48](https://user-images.githubusercontent.com/26849971/45893334-b156fe00-bdec-11e8-839c-9566d306e2ac.png)
I think , we need edit gtk.notebook's css like in io.elementary.code
![2018-09-21 22-22-52](https://user-images.githubusercontent.com/26849971/45893418-f9762080-bdec-11e8-9a1f-e7948ba6ecca.png)

**Comment by jlnr** [comment]
Related: https://github.com/elementary/stylesheet/issues/211

**Comment by ItsPossibleAlready** [comment]
OK
