### ISSUE TITLE
Pages like vpn, proxy, hotspot not included in URL specification

### ISSUE THREAD

**Issue by peteruithoven** [elementary/switchboard-plug-network#133]
Why aren't pages like VPN, Proxy and hotspot included in the [URL specification](https://docs.google.com/document/d/1N0uqNtVXEFn3cLgNMeN75mP_dpMpCco-7uw5PKow-_Q/edit?usp=sharing)? Url's like:
- network/vpn
- network/proxy
- network/wireless
- network/hotspot

A possibly related issue is that the [plug's `search`](https://github.com/elementary/switchboard-plug-network/blob/master/src/Plug.vala#L197-L210) lists a few keywords, enabling search, but they don't enable forwarding to specific views, unlike other plugs like Displays and Keyboard.

For pages like Wireless and Hotspot it might get tricky on devices that don't support wireless, but maybe we can show /forward to a page like the current `no-devices-info` or `airplane-mode-info`?

Implementing this would also enabling searching on these items in the Applications menu, see: https://github.com/elementary/applications-menu/pull/133

**Comment by peteruithoven** [comment]
The System Settings Schema Specification has been moved to the Switchboard wiki:
https://github.com/elementary/switchboard/wiki/System-Settings-Schema-Specification

**Comment by danrabbit** [comment]
I'm gonna close this for similar reasons to the a11y one. The spec is just meant to be a minimum cross-desktop list. Subpages are too implementation specific and search is working for these settings already
