### ISSUE TITLE
Unable to report .ovpn on Juno

### ISSUE THREAD

**Issue by louis993546** [elementary/switchboard-plug-network#138]
How to reproduce:
- Obtain a copy of Private Internet Access OpenVPN configuration via the "OpenVPN Configuration Generator"
- Select the following
    - OpenVPN 2.4 or newer
    - Linux
    - Europe/DE Berlin
    - UDP/1198 + RSA-2048 + AES-128-CBC + SHA1
- Generate and obtain the `.ovpn`
- Open System Settings
- "Network"
- "VPN"
- Click the "+" icon
- Select "Import a saved VPN configuration" from dropdown
- Select the `.ovpn` file
- This screenshot

![screenshot from 2018-10-21 09 38 09 2x](https://user-images.githubusercontent.com/3873011/47264330-10f01880-d515-11e8-8af1-07f1898a4247.jpeg)

And once you click OK, #122 happens until you close System Settings and open it back up again.

If you guys need a copy of the OpenVPN config, I would love to help, but not here, but somewhere more private.

**Comment by devnix** [comment]
Same problem, to connect to a vpn I have to use the openvpn command line tool.

**Comment by CodingSpiderFox** [comment]
@louis993546 does the bug still occur?

**Comment by louis993546** [comment]
> @louis993546 does the bug still occur?

Sorry I haven't used eOS (or any Linux distro) for a while 😅 so no idea

**Comment by CodingSpiderFox** [comment]
I'd suggest closing the issue then. Probably resolved long time ago
