### ISSUE TITLE
Il wi fi di ubuntu è veramente pessimo

### ISSUE THREAD

**Issue by GiulioFerr** [elementary/switchboard-plug-network#143]
Il wi fi tende a non prendere, e ha una percezione veramente pessima infatti pur essendo vicino al modem prende poco e niente. Per favore mi potete dire se è possibile risolvere questo problema?

**Comment by peteruithoven** [comment]
Thanks for reporting, but we require issues to be posted in English. 
Looking at the translation this sounds more like a support question than a bug, I'd recommend checking our stackexchange: 
https://elementaryos.stackexchange.com/
