### ISSUE TITLE
Wifi Toggle Is Absent

### ISSUE THREAD

**Issue by melee-man** [elementary/switchboard-plug-network#145]

**Comment by peteruithoven** [comment]
Please clarify. Maybe add a sentence or 2. Include a screenshot.

**Comment by melee-man** [comment]
> Please clarify. Maybe add a sentence or 2. Include a screenshot.

I'm new to Linux and I installed Elementary OS a few days ago but there is no toggle for Wifi. The OS only recognizes LAN cables and USB tethering. I run windows 10 and I never experienced this issue. Please help!
![screenshot from 2018-12-07 22-30-10](https://user-images.githubusercontent.com/32987310/49671208-5c2f9d80-fa67-11e8-9258-56c56d129717.png)

**Comment by peteruithoven** [comment]
Thanks for the clarifications and welcome to Linux
I'm afraid this isn't an issue of the Network settings, this is more likely a wireless card driver issue. These drivers are generally the same as on Ubuntu, the OS that elementary is build on top of. If you're using elementary OS Juno that's Ubuntu 18.04. (You can check these versions in the About settings.)

I'd suggest searching online on the combination of for example "ubuntu" and you're wireless card or computer model, there are most likely more people with the same issue. 
You could also check the elementary OS specific StackExchange: https://elementaryos.stackexchange.com/

Good luck!

**Comment by melee-man** [comment]
Thank you very much.
