### ISSUE TITLE
Unable to change WiFi connection

### ISSUE THREAD

**Issue by mike9251** [elementary/switchboard-plug-network#147]
I can't change my WiFi connection (the one I connected to during OS installation). When I click on another connection, it doesn't ask password but shows red exclamation mark and automatically starts connecting to the net I was connected before.
What can be the issue? How to fix it? Thanks.

**Comment by mike9251** [comment]
Managed to solve the issue in an unexpected way - before connecting to any WiFi connection go to 'Edit Connections...' and remove the connection with '-'. After that connecting to this connection it is needed to enter the password and connection gets established.
Still I think it is not the expected behavior, hope it will be fixed in the future.

**Comment by mike9251** [comment]
Hi worldofpeace!
Have you touched the gnome-keyring? I deleted it when Chromium started to ask for password during every launch. Now I have installed the gnome-keyring (got rid of the annoying Chromium's password request in a different way) and it seems switching between wifi connections works fine (without deleting them first). I think the problem was somehow related the deleted gnome-keyring.

**Comment by worldofpeace** [comment]
> Have you touched the gnome-keyring? I deleted it when Chromium started to ask for password during every launch.


I think using the deprecated `libgnome-keyring` has that bug.

> Have you touched the gnome-keyring?

No, though that is an interesting link that I will investigate.
