### ISSUE TITLE
Low Wifi Signal

### ISSUE THREAD

**Issue by tumchandara** [elementary/switchboard-plug-network#148]
I use dual boot on Window 8.1 (64Bit) and Elementary OS 5.0 Juno (64bit). The problem is whenever I use window 8.1 the wifi signal is full but when I switch to use Elementary the wifi is only 1 and sometime it disconnect (And i had to restart it) for some reason IDK. Is it just me or it the issues. Please response Thanks.

**Comment by peteruithoven** [comment]
Thanks for reporting. This isn't really related to the System settings network page though. This might be a drivers issue, which we graciously inherit from Ubuntu / Debian. 
You could try doing some research using your network card name and "Ubuntu".
