### ISSUE TITLE
Mark a network as metered

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-network#165]
Network manager already supports guessing and setting a connection as metered, i.e. if it's coming from a tethered Android phone or a 4G modem. We should expose that in settings so users have control over it.

**Comment by cassidyjames** [comment]
It looks like GNOME largely copied the network manager dialog contents into GNOME Control Center (did I get that right, @GeorgesStavracas?), and they have that check in that dialog.

**Comment by GeorgesStavracas** [comment]
Not an exact copy, but almost. That check was added by [1] and [2].

[1] https://gitlab.gnome.org/GNOME/gnome-control-center/commit/a37d04df42d20cb74b489d156e712f78922e4a81
[2] https://gitlab.gnome.org/GNOME/gnome-control-center/commit/24abbcf3030af2bfb3e64c17fe746539e0864e31
