### ISSUE TITLE
Translation problem : src/Widgets/EtherInterface.vala is missing ?

### ISSUE THREAD

**Issue by romdef** [elementary/switchboard-plug-network#178]
On Juno, in the Switchboard Plug Network, on french translated version, the 'Wired' input is not translated.
I checked the Weblate and I found it :
https://l10n.elementary.io/translate/switchboard/switchboard-plug-networking/fr/?checksum=&offset=&q=Wired&search=substring&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=

but it seems to be linked to a missing source file src/Widgets/EtherInterface.vala : 
https://github.com/elementary/switchboard-plug-networking/blob/master//src/Widgets/EtherInterface.vala#L57

I'm not a reporting specialist. Maybe it explains why the string is not translated in french ?!

**Comment by danrabbit** [comment]
It looks like the weblate git repo has merge conflicts. I'll try to resolve manually. Sorry for the inconvenience!

**Comment by danrabbit** [comment]
Should be resolved. Thanks for alerting us of the issue!
