### ISSUE TITLE
Wifi gets disabled after a few hours

### ISSUE THREAD

**Issue by shade379** [elementary/switchboard-plug-network#180]
I am running eOS 5.0 Juno on an HP Envy 15t i7-6500U intel HD 520 and everything is updated. 

This started to happen recently in the past two weeks. When using the laptop, after a few hours the wifi gets disabled and i get a notification saying wifi has disconnected and the vpn failed to connect. (I have my wifi connection set to auto connect to a vpn through openvpn). When this happens, clicking the wifi icon on the wingpanel shows no "wireless" section like normal but instead only shows my vpn connection options.

This is fixed by restarting the laptop but always happens again after a few hours.

**Comment by peteruithoven** [comment]
I'm afraid this is not the right place for this issue. The network settings can't help with this. This is most likely a driver issue. 
I'd advice searching online for your laptop or network card in combination with "ubuntu" since drivers is something we thankfully inherit from Ubuntu.
