### ISSUE TITLE
Pages do not load up even when wifi is connected

### ISSUE THREAD

**Issue by sourabhawasthi** [elementary/switchboard-plug-network#183]
Hi,

Everytime after I start-up my system, computer connects to a working wifi network but pages do not load. I have to toggle wifi multiple times to get it working  which is quite frustrating.

Please look in to this.

**Comment by peteruithoven** [comment]
Seeing you post this in the network settings repo suggest pages in the settings? If it's not this is not the right place for this issue. It's probably an aspect we thankfully inherit from Ubuntu, seeing they have a much larger user base I'd suggest you research how people on Ubuntu have solved this.
