### ISSUE TITLE
Select Lan network leads to corrupt window

### ISSUE THREAD

**Issue by flaminestone** [elementary/switchboard-plug-network#196]
Hello.
I have some problems with selecting lan network setting - setting windows is closed after select lan.
If i try to select lan from wingpanel indicator - all wingpanel will corrupted, and lan is not on.
I can attach all the logs if you tell me where they are placed.
![gifout](https://user-images.githubusercontent.com/6047261/64770138-45b5f580-d555-11e9-851c-4df21e5c6079.gif)
Can anybody help me, please?
elementary OS 5.0 Juno (last updates at this moment)

**Comment by Appeltabak** [comment]
@flaminestone This is something I experienced when I removed all wired connections from the network settings (see #181). I was able to recover the network by executing `nmcli device connect <network-inferface>`.

**Comment by flaminestone** [comment]
@Appeltabak yes, you are right.
I have no problem with interface after enabling network via your command and creating network setting.

**Comment by flaminestone** [comment]
Close because this issue is a part of #181
