### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by poweray** [elementary/switchboard-plug-network#201]
My xps 15 upgrade the wifi to Intel AX200,but only buletooth worked,wifi not found .Can anybody help me,how to install the dirver? thanks!

root@hairui-XPS-15-9550:/home/hairui# rfkill list
0: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no

**Comment by arshubham** [comment]
Linux support for AX200 was added in linux in early 2019. You might want to update to hwe kernel to get the support. https://blog.elementary.io/updates-for-august-2019/#get-the-hwe-update-today

https://www.phoronix.com/scan.php?page=news_item&px=Intel-WiFi-6-AX200-Cyclone-Peak
