### ISSUE TITLE
wifi option is not availabe 

### ISSUE THREAD

**Issue by pushpraj2164** [elementary/switchboard-plug-network#204]
just installed the elementary os but its not showing wifi option on hp-15 bs 576 tx

**Comment by kgrubb** [comment]
This seems to be a common issue with the realtek wifi cards in some HP laptops. Perhaps this will help you get it working: http://ubuntuhandbook.org/index.php/2018/08/no-wifi-adapter-found-hp-laptops-ubuntu-18-04/

**Comment by arshubham** [comment]
Marking it as out of scope since it is a driver issue.
