### ISSUE TITLE
🐞: Switchboard crashes when Mobile Broadband connection is toggled

### ISSUE THREAD

**Issue by yozachar** [elementary/switchboard-plug-network#260]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
Switchboard crashes while enabling Mobile Broadband on `switchboard-plug-network`.

### To Reproduce
Steps to reproduce the behaviour:
1. Open up network plugin section in the switchboard.
2. Connect a modem / dongle. I was using [this (Lava product)](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP._cdf_muZsm6PIxwSqXelUQAAAA%26pid%3DApi&f=1).
3. After a few moments Dongle / Modem is activated (I had a green LED indicator on the device), the dongle is discovered and the `Mobile Broadband` section appears.
4. Click on the toggle button to connect.
5. Switchboard crashes with segmentation fault.

### Expected behaviour
My system connects to the internet via the broadband without any errors.

### Crash!
![issue](https://user-images.githubusercontent.com/38415384/80302180-1becce80-87c6-11ea-9190-e335b403d89a.gif)

### When the Dongle was not activated
![Screenshot from 2020-04-25 22-05-48](https://user-images.githubusercontent.com/38415384/80300720-b47e5100-87bc-11ea-91b9-0d029dd69409.png)

### Toggle & Highlight Error

| Toggle-On / Highlight-Off | Toggle-Off / Highlight-On |
| --- | --- |
| ![Screenshot from 2020-04-26 12-06-00](https://user-images.githubusercontent.com/38415384/80300724-b9db9b80-87bc-11ea-85ef-25d79a4a0bbf.png) | ![Screenshot from 2020-04-26 12-06-04](https://user-images.githubusercontent.com/38415384/80300725-bb0cc880-87bc-11ea-9107-bc6424c27131.png)  |

## Logs
- In as seen in the `.gif`, `io.elementary.switchboard` crashes with `[1]    20213 segmentation fault  io.elementary.switchboard`.
- I tried running `gdb io.elementary.switchboard` but it ends up saying: `Reading symbols from io.elementary.switchboard...(no debugging symbols found)...done.`

## Platform Information
![Screenshot from 2020-04-26 13-27-49](https://user-images.githubusercontent.com/38415384/80301438-be568300-87c1-11ea-9eb9-39c683792718.png)

- [ ] <s>I'm using the latest version from git that I've manually compiled</s>
- [X] I'm using the latest released stable version

## Additional context
1. I opened this one as a new issue due to the lack of clarity in #244.
2. Should this be move to [Switchboard](https://github.com/elementary/switchboard)?

**Comment by FlyinPancake** [comment]
I am experiencing the same issue, on eOS 6
Here's my setup.
![Screenshot from 2021-05-14 12-52-24@2x](https://user-images.githubusercontent.com/36113055/118260994-484bb980-b4b3-11eb-80dd-ecceaf53493c.png)
![Screenshot from 2021-05-14 12-53-24@2x](https://user-images.githubusercontent.com/36113055/118261102-644f5b00-b4b3-11eb-985b-2070159ca208.png)
Disabling ModemManager with systemd enables me to get into network settings, but that's not really ideal.

**Comment by casasfernando** [comment]
I'm having a very similar issue in Odin (stable release).
I can use my LTE modem without any problems but I was not able to configure it using Switchboard's Network plugin because when the modem is plugged to the laptop, I'm not even able to open the Network plugin. Switchboard will close right away.
On the other hand if I remove the modem from the USB port I can access Switchboard's Network plugin without any issues.
As a workaround I configured the LTE connection using Network Manager's `nm-connection-editor`.

Starting and stopping the LTE connection from wingpanel's network indicator works just fine.

I tried to run `io.elementary.switchboard` from the terminal and these are the errors I get when trying to open the Network plugin while the LTE modem is plugged-in:

```
(io.elementary.switchboard:12436): Gtk-CRITICAL **: 16:59:32.573: gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed
**
Gtk:ERROR:../../../../gtk/gtkwidget.c:12412:gtk_widget_real_map: assertion failed: (_gtk_widget_get_realized (widget))
Bail out! Gtk:ERROR:../../../../gtk/gtkwidget.c:12412:gtk_widget_real_map: assertion failed: (_gtk_widget_get_realized (widget))
Aborted
```

![image](https://user-images.githubusercontent.com/15861819/129450547-4db666cc-0bb1-456a-b103-fab70e8b93bd.png)

![image](https://user-images.githubusercontent.com/15861819/129450561-693f6edf-1dee-448e-a306-92f86b2cdfee.png)

**Comment by vividhaditya** [comment]
The issue is dragged on to Odin too and no fix yet.

**Comment by casasfernando** [comment]
In case it helps to progress this bug investigation I collected a backtrace using gdb:

```
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from io.elementary.switchboard...
(No debugging symbols found in io.elementary.switchboard)
(gdb) run
Starting program: /usr/bin/io.elementary.switchboard 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5ac3700 (LWP 8427)]
[New Thread 0x7ffff52c2700 (LWP 8428)]
[New Thread 0x7fffed58e700 (LWP 8430)]
[New Thread 0x7fffe585e700 (LWP 8431)]

(io.elementary.switchboard:8423): Gtk-CRITICAL **: 08:03:17.630: gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed
**
Gtk:ERROR:../../../../gtk/gtkwidget.c:12412:gtk_widget_real_map: assertion failed: (_gtk_widget_get_realized (widget))
Bail out! Gtk:ERROR:../../../../gtk/gtkwidget.c:12412:gtk_widget_real_map: assertion failed: (_gtk_widget_get_realized (widget))

Thread 1 "io.elementary.s" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff70aa859 in __GI_abort () at abort.c:79
#2  0x00007ffff7e90b43 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7eedcef in g_assertion_message_expr () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff7745ddc in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007ffff75e4ab6 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ffff7c46965 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff7c65b48 in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff7c660f3 in g_signal_emit () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff775171a in gtk_widget_map () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff75f2369 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff752ba83 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff7c46708 in g_closure_invoke () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff7c5a962 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff7c65bbe in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff7c660f3 in g_signal_emit () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff775171a in gtk_widget_map () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff752ba83 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff7c46965 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff7c65b48 in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff7c660f3 in g_signal_emit () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff775171a in gtk_widget_map () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff7680836 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007ffff752ba83 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff7681395 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007ffff7c46965 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff7c65b48 in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff7c660f3 in g_signal_emit () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff775171a in gtk_widget_map () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007ffff75b9d30 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007ffff752ba83 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007ffff7c46965 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007ffff7c65b48 in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff7c660f3 in g_signal_emit () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff775171a in gtk_widget_map () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#35 0x00007ffff7633d66 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#36 0x00007ffff752ba83 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#37 0x00007ffff7c46a56 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#38 0x00007ffff7c65b48 in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#39 0x00007ffff7c660f3 in g_signal_emit () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#40 0x00007ffff775171a in gtk_widget_map () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#41 0x00007ffff77518d3 in gtk_widget_set_child_visible () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#42 0x00007ffff72c1008 in ?? () from /lib/x86_64-linux-gnu/libhandy-1.so.0
#43 0x000055555555d395 in ?? ()
#44 0x00007ffff7ec504e in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#45 0x00007ffff7ec5400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007ffff7ec56f3 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007ffff75fe37d in gtk_main () from /lib/x86_64-linux-gnu/libgtk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--c
#48 0x000055555555f22f in ?? ()
#49 0x00007ffff7c46a56 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#50 0x00007ffff7c65b48 in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#51 0x00007ffff7c660f3 in g_signal_emit () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#52 0x00007ffff7d74d98 in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
#53 0x00007ffff7d74f52 in g_application_run () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
#54 0x000055555555d131 in main ()
(gdb) quit
A debugging session is active.

	Inferior 1 [process 8423] will be killed.

Quit anyway? (y or n) y
```

Thanks.
