### ISSUE TITLE
elementary os wifi disabled problem

### ISSUE THREAD

**Issue by omenapex** [elementary/switchboard-plug-network#277]
i am using a hp pavilion laptop. I've been using elementary os 5.1.7 Hera version for 1 week. When I closed and opened the cover of my computer, I could not connect to WiFi. Although wifi is active, it did not see my internet or any other internet. After restarting the computer, this error was fixed. How can I solve this problem without restarting the computer? 

ı use google translate, sorry if there is a typo

**Comment by cassidyjames** [comment]
@omenapex thanks for opening an issue! Unfortunately we're unable to help with hardware-specific issues on GitHub, as the team does not have every possible hardware combination, and it's ultimately up to the proprietary drivers for that sort of behavior. We can recommend you check out our community-powered support site at [elementaryos.stackexchange.com](https://elementaryos.stackexchange.com), though, where there may be other users with the same or similar hardware.
