### ISSUE TITLE
Add WireGuard VPN support

### ISSUE THREAD

**Issue by tonilampela** [elementary/switchboard-plug-network#286]
Consider adding support for WireGuard VPN configuration and management into elementary OS graphical Network management tool. 

WireGuard is quickly replacing OpenVPN as more modern and robust VPN protocol, but currently with elementary OS you need to rely on CLI tools to manage WireGuard connections and configurations.

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/switchboard-plug-network/pull/338
