### ISSUE TITLE
Network Wired flapping

### ISSUE THREAD

**Issue by zimbawe998** [elementary/switchboard-plug-network#312]
Usually i use Wireless.
As soon as i attach an extra Wired nic, the Wired nic panel start to flap causing flapping on nic led also.
This is strange because the original os 6 works like a sharm.
Probably last two days update create this. Regression?

**Comment by andrewdbate** [comment]
I can confirm that I am having the same issue (as shown in the video) on multiple computers running elementary OS 6. On each of these machines, the wired Ethernet will not connect until I close the Network Settings app. The wired Ethernet then connects immediately as shown in the wingpanel.

I get the same rapidly connecting/disconnecting behaviour when I toggle off Airplane Mode (i.e., I can toggle on Airplane Mode and it works as expected, but when I toggle it off to connect to the network again I get the behaviour shown in the video). The wired Ethernet keeps rapidly connecting and disconnecting until I close the Network Settings app.

This is not just a UI glitch. By running a ping in a terminal window, I see that packets continue to be dropped until I close the Settings app, at which point the wingpanel shows the network as connected, and then all ping packets are received.
