### ISSUE TITLE
"Network Settings" in wingpanel doesn't take you to proper network menu

### ISSUE THREAD

**Issue by D0J0P** [elementary/switchboard-plug-network#321]
### What Happened?

When clicking on "Network Settings" in wingpanel-indicator-network, while connected to WiFi, will take me to the Wired category in switchboard-plug-network instead of Wireless. 

### Steps to Reproduce

1. Connect to WiFi instead of Ethernet
2. Click on wingpanel-indicator-network 
3. Click "Network Settings"
4. It'll open up switchboard-plug-network in the Wired category instead of Wireless.

### Expected Behavior

That if you're connected to WiFi and click on "Network Settings" in wingpanel-indicator-network, you'll be taken to the Wireless settings in switchboard-plug-network, and if you're connected to Ethernet, you'll be taken to the Wired settings.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danrabbit** [comment]
It looks like Network settings doesn't currently set up any suburls so there's nothing more specific that the indicator can link to. So that would need to be added first. That would also make search results jump to the right pages so that would be nice.

**Comment by danirabbit** [comment]
Network settings now opens to the page of the network you are connected to :tada:
