### ISSUE TITLE
Typo in user interface: addresses is misspelled as adresses 

### ISSUE THREAD

**Issue by andrewdbate** [elementary/switchboard-plug-network#324]
### What Happened?

There is a typo in the user interface. See screenshot:
![Screenshot from 2021-11-19 02-27-40](https://user-images.githubusercontent.com/2998569/142556578-ed65fbc8-1596-4fa7-9724-a9aa9232e51f.png)

The red arrow points at the misspelling. The word _adresses_ should be spelled _addresses_.

### Steps to Reproduce

While waiting for a DHCP address the Network panel shows _Requesting adresses..._ but this is not spelled correctly.

I have grepped the master branch and checked that the misspelling is still on master.

### Expected Behavior

The correct spelling should be used.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment]
Nice catch!
