### ISSUE TITLE
Wired Network Connection is "Not managed" anymore

### ISSUE THREAD

**Issue by dandelionmood** [elementary/switchboard-plug-network#423]
### What Happened?

I installed Elementary OS 8 a couple days ago, everything was running smoothly.

After restarting the computer yesterday (and probably installing some updates) my internal ethernet connection is somehow not working anymore. Tried rebooting several times, tried reverting to the previous kernel version upon boot, nothing seems to fix it. I tried changing from X11 to Wayland and back, no change.

Thanks for your help!

### Steps to Reproduce

I don't know how to reproduce this, as this only thing I did was to use the computer and install the latest updates.

![Capture d'écran du 2024-12-15 15 33 24](https://github.com/user-attachments/assets/0d41f0e4-dd9d-4b45-9532-640b3f37c57b)

Interface is shown as "non pris en charge", which I would translate to "not managed" or "not handled".
The switch to enable the interface is disabled as well.

I tried plugging in 2 USB ethernet adapters that I had lying around, they are both displayed as being "not managed".

I was able to regain network by plugging and configuring a wifi dongle which was working out of the box. This tells me that the network stack as a whole is working indeed.

Side note : I'm using third party drivers for the graphics card. Probably unrelated but you never know.

### Expected Behavior

The wired connection should work with configuration, as it once did.

### OS Version

8.x (Circe)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Doing a `lshw` reveals that network interface is indeed disabled, so this is probably not related to the HMI, rather to something that occurred below.

````
           *-network DÉSACTIVÉ
                description: Ethernet interface
                produit: RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet Controller
                fabricant: Realtek Semiconductor Co., Ltd.
                identifiant matériel: 0
                information bus: pci@0000:03:00.0
                nom logique: enp3s0
                version: 06
                numéro de série: fc:aa:14:07:af:c5
                bits: 64 bits
                horloge: 33MHz
                fonctionnalités: pm msi pciexpress msix vpd bus_master cap_list ethernet physical
                configuration : broadcast=yes driver=r8169 driverversion=6.8.0-50-generic latency=0 link=no multicast=yes
                ressources : irq:18 portE/S:d000(taille=256) mémoire:f7100000-f7100fff mémoire:f2100000-f2103fff
````

**Comment by dandelionmood** [comment]
_Plot twist_, after running `apt upgrade` (I was already up-to-date) and `flatpak update` (turns out I had a lot of updates to catch up) using my backup connection and restarting one final time ... It finally worked again.

I have a hunch that the "automatic updates" options (which was enabled) might have not run completely and the system was stuck in between states. I'm disabling it for now.

**Comment by ryonakano** [comment]
Looks like some of these updates causes this issue.

```
user@VirtualBox-36929c8d:~$ apt list --upgradable 
Listing... Done
libnm0/noble-updates 1.46.0-1ubuntu2.2 amd64 [upgradable from: 1.46.0-1ubuntu2]
network-manager-config-connectivity-ubuntu/noble-updates 1.46.0-1ubuntu2.2 all [upgradable from: 1.46.0-1ubuntu2]
network-manager/noble-updates 1.46.0-1ubuntu2.2 amd64 [upgradable from: 1.46.0-1ubuntu2]
user@VirtualBox-36929c8d:~$ 
```

**Comment by teamcons** [comment]
Some other users had that issue and did the following:
From Discord:

it was nmcli not managing my device for some reason. Solved by creating a blank file in /etc/NetworkManager/conf.d/10-globally-managed-devices.conf

terminal:
> sudo touch /etc/NetworkManager/conf.d/10-globally-managed-devices.conf

**Comment by kaixoo** [comment]
Here's the post where I found the workaround for the issue: https://askubuntu.com/questions/71159/network-manager-says-device-not-managed

This seems to be a problem with NetworkManager upstream, perhaps we should report it there?

**Comment by ryonakano** [comment]
> This seems to be a problem with NetworkManager upstream, perhaps we should report it there?

No, this is because we're [overwriting](https://github.com/elementary/os/blob/4ef03d6b8a4e90288bbbed26a1ea7e65da7680ba/etc/config/includes.chroot/usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf) `/usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf` with the same filename that network-manager provides while building the iso. So, our config can be re-overwritten when network-manager is updated and causes this issue.

We should rename it so that it won't overwritten by upstream updates.

**Comment by ryonakano** [comment]
Closing as fixed in https://github.com/elementary/os/pull/745. Starting from the next daily and stable ISOs this fix takes effect.
