### ISSUE TITLE
Active VPN connections might be a list

### ISSUE THREAD

**Issue by febrezo** [elementary/switchboard-plug-network#66]
Currently `VPNPage.vala` considers active VPN connection as an item. However, NetworkManager considers the chance of having two different VPN connections at once. The `active_connection_item` should be an `active_vpn_list`.

**Comment by febrezo** [comment]
I'm adding some screenshots to illustrate the issue that seems to be linked to the management of VPN tunnels. NetworkManager supports simultaneous VPN connections since 1.2 as shown [here](https://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/NEWS#n244). 

The standard connection to a VPN looks like this:
![1-single-vpn](https://user-images.githubusercontent.com/1590496/29997165-c5816802-900c-11e7-862c-e4fdebef8004.png)
When clicking on another and if the connection fails for any reason, the old tunnel seems to be created as shown by `ifconfig`, but the Switchboard interface will show no connection in the GUI. Reloading the Switchboard (closing and reopening it), showed the correct information. By the way, meanwhil, the Wingpannel indicator was still showing the lock in the Wifi connection. 
![2- the error](https://user-images.githubusercontent.com/1590496/29997166-c585f32c-900c-11e7-8dba-04cc615ae57d.png)

The aforementioned was the one that made me notice that something was wrong with the management of the VPN information as something independent from Network Manager. I confirmed that when trying to get connected to a second VPN as show here. Both tunnels seems to be created, but only one is shown in the Switchboard. 

![3-multivpn](https://user-images.githubusercontent.com/1590496/29997167-c58661fe-900c-11e7-87f1-08a5dd91bbed.png)

**Comment by Philip-Scott** [comment]
I'm going to mark this as `needs design` since it will most likely need a UI change. 

@febrezo You mentioned clicking on a second VPN, but what's the limit? Can you have unlimited VPNs running at the same time? If that's the case, we might need to change the interface from being able to select one (like it's done with WiFi) to maybe either have each VPN be it's own page, or maybe having a switch on each network.

@febrezo I think that the network indicator has a way to change VPNs, does it? Because if so, the indicator might also need some changes :)

**Comment by febrezo** [comment]
@Philip-Scott That's a point. My use case was relevant so as to have access to some resources which were available in both VPN at the same time. In fact, I am not sure about how the outgoing traffic is being dealt in that use case. I'll dig into it.

@Philip-Scott I have shipped a different issue to report the bad behaviour when clicking in a different VPN without manually disconnecting as #67.
