### ISSUE TITLE
When connected to a VPN, chosing another one does not close 

### ISSUE THREAD

**Issue by febrezo** [elementary/switchboard-plug-network#67]
After getting connected to a VPN (indicator shows the lock), chosing another one by clicking on another tries to open a new VPN connection without closing the previous one (which is a use case explained in #66). The connection is never set up (because there is one already running) and if the user manually stops while it tries to get connected the VPN in the left menu will show a `Disconnected` message (although the indicator shows the lock because the original VPN connection is still active). As a result, the forgotten original VPN connection cannot be manually configured or disconected as usual.

Restarting the Switchboard will show VPN as `Connected` fixing the displaying issues previously said.

**Comment by xfbs** [comment]
I've experiences this behaviour too, and I believe selecting multiple VPN networks has messed up my kernel's routing table. Even after disconnecting from all, I've had some routes in it as 'default' that didn't work, meaning that I had to manually flush them.
